




###
get http://localhost:8000/api/users/getallusers
###
post http://localhost:8000/api/users/register
Content-Type: application/json

{
    "name":"satyam",
    "email":"satyam@gmail.com",
    "password":"satyam"
}


###
post http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email":"satyam@gmai.com",
    "password":"satyam"
}


###
get http://localhost:8000/api/current-user





PORT = 8000

MONOGOCONNECTIONURI=mongodb+srv://2309000satyam_db_user:YDmdh8FcqTBH3G7C@cluster0.8rpe2ln.mongodb.net/invoide_web_app?appName=Cluster0


NODE_ENV=production


ACCESS_TOKEN_SECRET="xIYjF4UDJ0lrul7wu9S7ofmXdFSH2tpdp7R7Iu8Q4dljkGGOl7QKSvX4yK9gqBJc"
REFRESH_TOKEN_SECRET="L..+[R:{[6RV?scZA|wz#.uH0HX4@}2o[Q(z-JdjDXDpZMZ:O;PD-2Ox2TI.=-.I"
ACCESS_TOKEN_EXPIRY=1d
REFRESH_TOKEN_EXPIRY=30
